export const values=[{id:1,name:"User 1", 
time:"12h", 
mainContent:"Tailwind CSS is awesome and it is CSS is awesome and Tailwind CSS is awesome and Tailwind CSS is awesome and",
 heartsCount:3},{id:2,name:"User 2", 
time:"Aug 1", 
mainContent:"Testing content",
 heartsCount:2},
 {id:3,name:"User 3", 
time:"22m", 
mainContent:"React",
 heartsCount:"2k"},
 {id:4,name:"User 4", 
time:"1d", 
mainContent:"Javascript is a programming language used in front-end",
 heartsCount:"1M"},{id:5,name:"User 1", 
time:"12h", 
mainContent:"Tailwind CSS is awesome and it is CSS is awesome and Tailwind CSS is awesome and Tailwind CSS is awesome and",
 heartsCount:3},{id:6,name:"User 2", 
time:"Aug 1", 
mainContent:"Testing content",
 heartsCount:2},
 {id:7,name:"User 3", 
time:"22m", 
mainContent:"React",
 heartsCount:"2k"},
 {id:8,name:"User 4", 
time:"1d", 
mainContent:"Javascript is a programming language used in front-end",
 heartsCount:"1M"},{id:9,name:"User 1", 
time:"12h", 
mainContent:"Tailwind CSS is awesome and it is CSS is awesome and Tailwind CSS is awesome and Tailwind CSS is awesome and",
 heartsCount:3},{id:10,name:"User 2", 
time:"Aug 1", 
mainContent:"Testing content",
 heartsCount:2},
 {id:11,name:"User 3", 
time:"22m", 
mainContent:"React",
 heartsCount:"2k"},
 {id:12,name:"User 4", 
time:"1d", 
mainContent:"Javascript is a programming language used in front-end",
 heartsCount:"1M"},{id:13,name:"User 1", 
time:"12h", 
mainContent:"Tailwind CSS is awesome and it is CSS is awesome and Tailwind CSS is awesome and Tailwind CSS is awesome and",
 heartsCount:3},{id:14,name:"User 2", 
time:"Aug 1", 
mainContent:"Testing content",
 heartsCount:2},
 {id:15,name:"User 3", 
time:"22m", 
mainContent:"React",
 heartsCount:"2k"},
 {id:16,name:"User 4", 
time:"1d", 
mainContent:"Javascript is a programming language used in front-end",
 heartsCount:"1M"}]